# Generated by Django 3.2.9 on 2021-11-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_alter_persona_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='edad',
        ),
    ]
